### ISSUE TITLE
Library does not work in other regions

### ISSUE THREAD

**Issue by geotrieu** [SleepWalker/tuya-cloud-api#2]
It appears that this only works in the EU region, as by the prefixUrl found in httpClient.ts
There are three other regions in addition to EU:
'https://openapi.tuyacn.com/v1.0'
'https://openapi.tuyaus.com/v1.0'
'https://openapi.tuyain.com/v1.0'

Would it be possible to add a selector of sorts to set the region where the API resides?

**Comment by SleepWalker** [comment]
Hello, @geotrieu. Sorry for the late answer. For some reason the notifications was disabled for this repo and I haven't notice that something was happened :sweat_smile: 

I'll release a fix in several hours

**Comment by geotrieu** [comment]
This is awesome, thank you!
